<?php
session_start();


require 'conexion.php';
	$conexion = conexion($db_config);
    $DATOSM = $conexion->prepare('CALL editar_datos_tutorado(:a_paterno,:a_materno,:nombre,:no_control,:sexo,:fechanac,:num_telefono,:email,:estado_civil,:nacionalidad,:entidad_origen,:lengua_indigena,:nombre_idioma_ind,:calle,:numero_interior,:colonia,:codigo_postal,:ciudad,:municipio,:estado,:escuela_procedencia,:entidad_procedencia,:nombre_empresa,:horario_trabajo,:especifricar_enfermedad,:espci_enf,:medicamento_que_tomas,:frecuencia_tomas_medicamento,:especifricar_discapacidad,:nombre_disc,:alergico,:especifricar_medicamento,:parentesco,:ap_paterno,:ap_materno,:nombre,:domiciio,:ciudad,:codigo_postal,:municipio,:estado,:telefono,:email,:celular,:ocupacion,:edad,:principal_sosten_economico,:cuantos_viven_encasa,:cuantos_hermanos_tienes,:hombres,:mujeres,:que_lugar_ocupas,:actualmente_vives_con,:cuantos_viven_actualmente_contigo,:cuantos_laboran,:acceso_internet_casa,:cuentas_con_computadora_lap,:especificar,:parentesco,:apellido_peterno,:apellido_materno,:nombre,:domiciio,:ciudad,:codigo_postal,:municipio,:estado,:telefono,:email,:celular,:id_usuario)');
                
$DATOSM->execute(array(':a_paterno' => $_POST['apellidop'],':a_materno'=> $_POST['apellidom'],':nombre'=> $_POST['NombreA'], ':no_control' => $_POST ['ncontrol'],':sexo' => $_POST['sexo'], ':fechanac' => $_POST['fecha'],':num_telefono' => $_POST['telefono'], ':email' => $_POST['correoE'], ':estado_civil' => $_POST['estadoC'], ':nacionalidad' => $_POST['Nacionalidad'], ':entidad_origen' => $_POST['EntidadOrigen'], ':lengua_indigena' => $_POST['hablanteI'],':nombre_idioma_ind' => $_POST['idiomaI'], ':calle' => $_POST['DomicilioA'], ':numero_interior' => $_POST['NumeroInt'], ':colonia' => $_POST['Colonia'],':codigo_postal' => $_POST['Cp'], ':ciudad' => $_POST['Ciudad'], ':municipio' => $_POST['municipio'], ':estado' => $_POST['estado'], ':escuela_procedencia' => $_POST['EscuelaP'], ':entidad_procedencia' => $_POST['EntidadP'], ':nombre_empresa' => $_POST['NombreE'], ':horario_trabajo' => $_POST['HorarioTrabajo'], ':especifricar_enfermedad' => $_POST['Enfermedad'], ':espci_enf' => $_POST['NombreEnfermedad'], ':medicamento_que_tomas' => $_POST['MedicamentoT'], ':frecuencia_tomas_medicamento' => $_POST['FrecuenciaT'], ':especifricar_discapacidad' => $_POST['Discapacidad'],':nombre_disc' => $_POST['DiscapacidadE'], ':alergico' => $_POST['Alergico'], ':especifricar_medicamento' => $_POST['AlergicoE'], ':parentesco' => $_POST['ParentescoT'], ':ap_paterno' => $_POST['apellidopaT'], ':ap_materno' => $_POST['apellidomaT'], ':nombre' => $_POST['NombreT'], ':domiciio' => $_POST['DomicilioAT'], ':ciudad' => $_POST['CiudadT'], ':codigo_postal' => $_POST['CpT'], ':municipio' => $_POST['municipioT'], ':estado' => $_POST['estadoT'], ':telefono' => $_POST['TelefonoT'], ':email' => $_POST['emailT'], ':celular' => $_POST['CelT'],':ocupacion' => $_POST['OcupacionT'], ':edad' => $_POST['edadT'], ':principal_sosten_economico' => $_POST['SostenE'], ':cuantos_viven_encasa' => $_POST['VivesAcon'], ':cuantos_hermanos_tienes' => $_POST['Chermanos'],':hombres' => $_POST['CHombre'], ':mujeres' => $_POST['CMujer'],':que_lugar_ocupas' => $_POST['Locupas'], ':actualmente_vives_con' => $_POST['VivesAcon'],':cuantos_viven_actualmente_contigo' => $_POST['CuantoVC'], ':cuantos_laboran' => $_POST['CLaboran'], ':acceso_internet_casa' => $_POST['AccesoInt'], ':cuentas_con_computadora_lap' => $_POST['CuentasConComputadora'],':especificar' => $_POST['EspecificaCp'], ':parentesco' => $_POST['ParentescoM'], ':apellido_peterno' => $_POST['apellidopaM'], ':apellido_materno' => $_POST['apellidomaM'], ':nombre' => $_POST['NombreM'] , ':domiciio' => $_POST['DomicilioATM'], ':ciudad' => $_POST['CiudadM'], ':codigo_postal' => $_POST['CpM'], ':municipio' => $_POST['municipioM'],':estado' => $_POST['estadoM'], ':telefono' => $_POST['TelefonoM'], ':email' => $_POST['emailM'], ':celular' => $_POST['celularM'], ':id_usuario' => $_POST['Id_Usuario']));
$DTBEDITARUSER = $DATOSM->fetch();

?>